---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldie
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldie-main
  labels:
    app: goldie
  annotations:
    io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/9000/TCP/HTTP>,<Egress/9007/TCP/HTTP>,<Ingress/9000/TCP/HTTP>"
spec:
  selector:
    matchLabels:
      component: goldie-main
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldie-main
        component: goldie-main
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: goldie
      containers:
      - name: server
        image: ghcr.io/sphinxgaia/goldie-main:basic
        imagePullPolicy: Always
        resources: {}
        ports:
        - name: http
          containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: goldie-main
  labels:
    app: goldie
spec:
  selector:
    component: goldie-main
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  # type: ClusterIP
  # change to NodePort if no LoadBalancer controller is available
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goldie-body
  labels:
    app: goldie
  annotations:
    io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/9007/TCP/HTTP>,<Egress/9000/TCP/HTTP>,<Ingress/9000/TCP/HTTP>"
spec:
  selector:
    matchLabels:
      component: goldie-body
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldie-body
        component: goldie-body
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: goldie
      containers:
      - name: server
        image: ghcr.io/sphinxgaia/goldie-body:basic
        imagePullPolicy: Always
        resources: {}
        ports:
          - name: http
            containerPort: 9000
        env:
          - name: PORT
            value: "9000"
          # - name: VERSION
          #   value: "blue"
---
apiVersion: v1
kind: Service
metadata:
  name: goldie-body
  labels:
    app: goldie
spec:
  selector:
    component: goldie-body
  ports:
    - name: http
      port: 9007
      protocol: TCP
      targetPort: http
  type: ClusterIP
  # clusterIP: None
# ---
# image: busybox
# command: 
# - /bin/sh
# args:
# - -c
# - |
#   sleep 15000sg-0e62c903aa055a466